services:

  mongo:
    image: mongo
    restart: always
    volumes:
      - spotube-mongo:/data/db

  backend:
    build: ./backend

    environment:
      - JWT_SECRET=${JWT_SECRET}
      - PUBLIC_SPOTIFY_CLIENT_ID=${PUBLIC_SPOTIFY_CLIENT_ID}
      - PUBLIC_SPOTIFY_SCOPES=${PUBLIC_SPOTIFY_SCOPES}
      - PUBLIC_SPOTIFY_REDIRECT_URI=${PUBLIC_SPOTIFY_REDIRECT_URI}
      - PUBLIC_SPOTIFY_CLIENT_SECRET=${PUBLIC_SPOTIFY_CLIENT_SECRET}

  frontend:
    build: ./frontend

    environment:
      - JWT_SECRET=${JWT_SECRET}
      - PUBLIC_SPOTIFY_CLIENT_ID=${PUBLIC_SPOTIFY_CLIENT_ID}
      - PUBLIC_SPOTIFY_SCOPES=${PUBLIC_SPOTIFY_SCOPES}
      - PUBLIC_SPOTIFY_REDIRECT_URI=${PUBLIC_SPOTIFY_REDIRECT_URI}

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx/prod:/etc/nginx/conf.d:ro
    depends_on:
      - frontend
      - backend

volumes:
  spotube-mongo: